paths:
  db_path: ./../data/taxi.db
  model_path: ./../model-registry/taxi.model
  model_custom_path: ./../model-registry/taxi_custom.model
ml:
  model_version: "1.0.0"
mlflow:
  mlruns: ./../model/mlruns
  model_name: taxi_trip_duration
